name: chocolatine

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  EXECUTABLES: "directory1/executableA,directory2/executableB"
  MIRROR_URL: " git@github.com:EpitechPGEPromo2029/B-DOP-200-PAR-2-1-chocolatine-sandra.kildemose-jorgensen.git"

jobs:
  check_conditions:
    name: Check conditions
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.result }}
    steps:
      - name: Check if in mirror repo
        id: check
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          if [ "$GITHUB_REPOSITORY" = " git@github.com:EpitechPGEPromo2029/B-DOP-200-PAR-2-1-chocolatine-sandra.kildemose-jorgensen.git" ]; then
            echo "result=false" >> $GITHUB_OUTPUT
          else
            echo "result=true" >> $GITHUB_OUTPUT
          fi

  check_coding_style:
    name: Check coding style
    needs: check_conditions
    if: needs.check_conditions.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run coding style check
        run: check.sh $(pwd) $(pwd)

    