name: chocolatine
run-name: ${{ github.actor }} choco's check

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  EXECUTABLES: "mysh"  # Change to your actual executable(s)
  MIRROR_URL: "git@github.com:SandraKildemose/chocolatine.git"

jobs:
  # First job: check coding style
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    if: github.repository != 'MIRROR_REPO_NAME'  # Prevent running in the mirror repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run coding style checker
        run: check.sh $(pwd) $(pwd)

      - name: Annotate coding style errors
        run: |
          input=/tmp/coding-style-reports.log
          while IFS= read -r line; do
            fields=($(echo "$line" | cut -d':' -f1-4))
            echo "::error title=${fields[2]} coding style error,file=${fields[0]},line=${fields[1]}::${fields[3]}"
          done < "$input"

      - name: Fail if coding style errors found
        run: |
          NB_ERROR=$(wc -l < /tmp/coding-style-reports.log)
          if [ "$NB_ERROR" -gt 0 ]; then
            exit 1
          fi

  # Second job: compile the program
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    needs: check_coding_style
    timeout-minutes: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile project
        run: make

      - name: Clean build files
        run: make clean

      - name: Verify executable(s)
        run: |
          for file in ${{ env.EXECUTABLES }}; do
            if [ ! -x "$file" ]; then
              echo "::error file=$file::File does not exist or is not executable"
              exit 1
            fi
          done

  # Third job: run the tests
  run_tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    needs: check_program_compilation
    timeout-minutes: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and run tests
        run: make tests_run

  # Final job: push to mirror if everything passed
  push_to_mirror:
    runs-on: ubuntu-latest
    needs: run_tests
    if: github.event_name == 'push'
    steps:
      - name: Checkout full git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}